---
argocd_namespace: argocd
argocd_chart: ../cluster/bootstrap/argocd
argocd_root_app_chart: ../cluster/bootstrap/root

argocd_crds:
  - applications.argoproj.io
  - applicationsets.argoproj.io
  - appprojects.argoproj.io
argocd_root_app_appsets:
  - system
  - observability
  - platform
  - apps
  - projects

argocd_root_app_repo_url: https://github.com/Sonic0/homelab
