---
vault_namespace: vault
vault_kubevault_version: v2025.2.10
vault_kubevault_license_file: "{{ playbook_dir }}/roles/k8s_apps/vault_secrets/kubevault-license.txt"
vault_kubevault_server_version: "1.18.4"

vault_pod: vault-0
vault_token: "{{ lookup('env', 'VAULT_TOKEN') or vault_token }}"
vault_token_k8s_secret_name: vault-root-token
vault_token_k8s_secret_key: k8s.70f48e5e-46af-44a2-9220-89b2bbb37d38.vault.vault-root-token

vault_secrets:
  - path: secret/common
    kv: foo=bar
  - path: secret/apps/guestbook
    kv: "user=admin
      password={{ lookup('env', 'GUESTBOOK_PASSWORD') }}"
