---
k3s_version: v1.31.6+k3s1
k3s_cluster_context_name: k3s-homelab
k8s_init_inventory_path: "{{ playbook_dir }}/inventories/k3s_{{ k8s_cluster_name }}"

k8s_cluster_controlplane_group: k8s_controlplane_{{ k8s_cluster_name }}
k8s_cluster_workers_group: k8s_workers_{{ k8s_cluster_name }}
k8s_cluster_lb_group: k8s_lb_{{ k8s_cluster_name }}

k8s_cluster_user_home: /home/{{ ansible_user }}/.kube
k8s_cluster_kubeconfig_remote: "{{ k8s_cluster_user_home }}/config"
k8s_cluster_kubeconfig_localhost: "{{ lookup('env', 'HOME') }}/.kube/config"

k8s_cluster_kubeadm_config: /etc/kubernetes/kubeadm-config.yml
# k8s_cluster_control_plane_endpoint: 192.168.13.254

k8s_cluster_pod_network: 10.10.0.0/16
# renovate: depName=projectcalico/calico
k8s_cluster_pod_network_version: v3.29.1
k8s_cluster_pod_network_manifest_url: https://raw.githubusercontent.com/projectcalico/calico/{{ k8s_cluster_pod_network_version }}/manifests/calico.yaml
k8s_cluster_pod_network_manifest_dir: "{{ k8s_cluster_user_home }}/calico"
k8s_cluster_pod_network_manifest: "{{ k8s_cluster_pod_network_manifest_dir }}/calico.yaml"
