apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: pihole-secret
  data:
    - secretKey: admin-password
      remoteRef:
        key: secret/pihole
        property: admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
