---
# credit: https://johnscs.com/remove-proxmox51-subscription-notice/
- name: Remove subscription nag message
  ansible.builtin.replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: '(\s+)(Ext\.Msg\.show\(\{\s+title\: gettext\(.No valid subscription)'
    replace: '\g<1>void({ //\g<2>'
    backup: true
  register: replace_proxmoxlib_js
  notify: restart pveproxy

- name: Print subscription prompt backup file
  ansible.builtin.debug:
    msg: "{{ replace_proxmoxlib_js.backup_file }}"
  when: replace_proxmoxlib_js.changed and not replace_proxmoxlib_js.failed
