---
- name: Remove pve-enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/pve {{ ansible_facts.distribution_release }} pve-enterprise
    filename: pve-enterprise
    state: absent
    update_cache: false

- name: Remove ceph-enterprise repository
  ansible.builtin.apt_repository:
    repo: deb https://enterprise.proxmox.com/debian/ceph-quincy {{ ansible_facts.distribution_release }} enterprise
    filename: ceph
    state: absent
    update_cache: true

- name: Add pve-no-subscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve {{ ansible_facts.distribution_release }} pve-no-subscription
    filename: pve-no-subscription
    state: present
    update_cache: true

- name: Add ceph-no-subscription repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/ceph-quincy {{ ansible_facts.distribution_release }} no-subscription
    filename: ceph-no-subscription
    state: present
    update_cache: true
