external-dns:
  provider:
    name: pihole

  sources:
    - service
    - ingress

  # Policy: upsert-only per non eliminare record gestiti manualmente
  policy: upsert-only

  # Registry: noop perché PiHole non supporta record TXT per il tracking
  registry: noop

  extraArgs:
    pihole-server: "http://pihole-web.apps.svc.cluster.local"
    pihole-api-version: "6"

  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: password
    - name: EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY
      value: "true"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

  # Security context a livello di Pod
  podSecurityContext:
    fsGroup: 65534

  # Security context a livello di Container (opzionale ma raccomandato)
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # Crea il ServiceAccount
    create: true
    # Nome del ServiceAccount (se vuoi specificarlo esplicitamente)
    name: "external-dns"
    # Automount token API
    automountServiceAccountToken: true

  rbac:
    # Crea ClusterRole e ClusterRoleBinding con i permessi necessari
    # Il chart include automaticamente: services, endpoints, pods, nodes,
    # ingresses, e altri resource types necessari
    create: true

  deploymentStrategy:
    type: Recreate

  # Numero di repliche
  replicas: 1

  # Logging
  logLevel: info
  logFormat: json

  # Intervallo di sincronizzazione
  interval: "1m"

  # Trigger on events (oltre all'intervallo)
  triggerLoopOnEvent: false

  # Probes (valori di default del chart)
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 2
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
