---
plugin: community.general.nmap
#address: '192.168.1.0/24' # Using ANSIBLE_NMAP_ADDRESS env var
port: 3128
open: true
strict: false
use_extra_vars: true
compose:
  ansible_user: "{{ proxmox_init_user }}"
  ansible_password: "{{ proxmox_init_user_pwd }}"
