---
pve_template_image_url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
pve_template_image_path: /tmp/{{ pve_template_image_url | basename }}
pve_template_vmid: "{{ lookup('ansible.builtin.env', 'STAGE0_VM_ID') }}"
pve_template_name: "{{ lookup('ansible.builtin.env', 'STAGE0_VM_NAME') }}"
pve_template_description: Built with Ansible
pve_template_cores: 2
pve_template_memory: 2048
pve_template_disk_size: 5
pve_template_disk_storage: local-zfs
pve_template_disk_name: "{{ pve_template_disk_storage }}:vm-{{ pve_template_vmid }}-disk-0"
# pve_template_disk_storage: spsrv-proxmox
# pve_template_disk_name: "{{ pve_template_disk_storage }}:{{ pve_template_vmid }}/vm-{{ pve_template_vmid }}-disk-0.qcow2"
pve_template_net_br: vmbr0
# pve_template_net_vlan: 13

pve_template_destroy: false
