---
- name: K3S | Install K3S Ansible Collection
  ansible.builtin.command: ansible-galaxy collection install git+https://github.com/k3s-io/k3s-ansible.git
  register: ansible_collection_result
  failed_when: ansible_collection_result.rc != 0
  run_once: true

# - name: K3S | Execute the k3s_token.yml task
#   ansible.builtin.import_tasks: k3s_token.yml
#   tags: ["init", "k3s", "setup"]

- name: K3S | Create Ansible group vars from template
  ansible.builtin.template:
    src: k3s_group_vars.yml.j2
    dest: "{{ playbook_dir }}/group_vars/k3s_{{ k8s_cluster_name }}.yml"

- name: Print the generated group_vars file
  ansible.builtin.debug:
    msg: "{{ lookup('file', playbook_dir + '/group_vars/k3s_' + k8s_cluster_name + '.yml') }}"

- name: k3S | Verify the existence of the inventory file
  ansible.builtin.stat:
    path: "{{ k8s_init_inventory_path }}"
  register: inventory_file

- name: k3S | Fail if the inventory file does not exist
  ansible.builtin.fail:
    msg: "The inventory file {{ k8s_init_inventory_path }} does not exist."
  when: not inventory_file.stat.exists
