---
pihole:
  replicaCount: 1
  maxSurge: 2

  # -- Set Pi-hole admin password
  admin:
    existingSecret: pihole-password
    password: password

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
      - 127.0.0.1
      - 1.1.1.2

  # -- Service configuration
  serviceDns:
    type: LoadBalancer
    loadBalancerIP: 192.168.20.51
    annotations:
      metallb.universe.tf/address-pool: server-lan-pool
      metallb.universe.tf/allow-shared-ip: pihole-svc

  serviceDhcp:
    enabled: false

  # serviceWeb:
  #   type: LoadBalancer
  #   loadBalancerIP: 192.168.20.51
  #   annotations:
  #     metallb.universe.tf/address-pool: server-lan-pool
  #     metallb.universe.tf/allow-shared-ip: pihole-svc

  # -- DNS Configuration
  DNS1: "1.1.1.2"
  DNS2: "1.0.0.2"

  # -- Persistent storage
  persistentVolumeClaim:
    enabled: true
    size: 1Gi
    storageClass: "local-path"

  # -- Ingress settings for Traefik
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: apps-dashboard-prefix@kubernetescrd
      cert-manager.io/cluster-issuer: "local-root-ca" # The self-signed CA issuer
      cert-manager.io/subject-organizations: "Homelab"
      cert-manager.io/subject-organizationalunits: "Deployment"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: "Pi-hole DNS server"
      gethomepage.dev/group: Network
      gethomepage.dev/icon: pihole.png
      gethomepage.dev/name: Pi-hole
      gethomepage.dev/widget.type: "pihole"
      gethomepage.dev/widget.url: "https://pihole.srv.home.lan/admin"
      gethomepage.dev/pod-selector: ""
    path: /
    hosts:
      - pihole.srv.home.lan
    tls:
      - hosts:
          - pihole.srv.home.lan
        secretName: pihole-tls

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  doh:
    enabled: true
    pullPolicy: Always

  dnsmasq:
    customDnsEntries:
      - address=/switch.net.home.lan/192.168.20.20
      - address=/sonicwallap.net.home.lan/192.168.20.21
      - address=/zyxelap.net.home.lan/192.168.20.22

    customCnameEntries:
      - cname=sonic.ap,sonicwallap.net.home.lan
      - cname=zyxel.ap,zyxelap.net.home.lan

  extraEnvVars:
    TZ: "Europe/Rome"
