---
- hosts: all

  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: set initialize 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_initialize:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  roles:
    - role: proxmox/init
      tags:
        - always

  post_tasks:
    - name: set initialize 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_initialize:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"
