---
- name: k8s cluster init
  hosts: all
  gather_facts: true
  tags: ["init", "k3s", "setup"]

  roles:
    - role: timezone
      become: true

- name: K3S pre
  hosts: localhost
  gather_facts: true
  tags: ["init", "k3s", "setup"]

  roles:
    - role: k8s/cluster_init

- name: k8s apps
  hosts: localhost
  gather_facts: true
  tags: ["init", "k3s", "apps"]
  environment:
    K8S_AUTH_CONTEXT: k3s-homelab

  roles:
    - { role: k8s_apps/argocd }
#     - { role: k8s_apps/vault_secrets }
