apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: regcred
spec:
  externalSecretName: regcred
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      template:
        type: kubernetes.io/dockerconfigjson
        metadata:
          annotations: {}
          labels: {}
        data:
          .dockerconfigjson: {{ `"{{ .dockerconfigjson }}"` }}
    data:
      - secretKey: dockerconfigjson
        remoteRef:
          key: secret/k8s-registry-auth
          property: dockerconfigjson
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
